server:
  port: 8085
spring:
  application.name: shop-service

  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      name: db-docker,shop-service-docker,email,eureka
  config.import: optional:configserver:config-server