server:
  port: 8085
spring:
  application.name: shop-service

  # database
  cloud:
    config:
      uri: http://localhost:8888
      name: database,email

  # set up initial data
  sql.init.mode: always
  jpa.defer-datasource-initialization: true

# eureka
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl.defaultZone: http://localhost:8761/eureka/