server:
  port: 8086

spring:
  application.name: notification-service

  #database
  cloud:
    config:
      uri: http://localhost:8888
      name: email

 #kafka
  kafka:
    consumer:
      enable-auto-commit: true
      bootstrap-servers: localhost:9092
      group-id: my-group
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.LongDeserializer
        spring.deserializer.value.delegate.class: org.apache.kafka.common.serialization.StringDeserializer

#eureka
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl.defaultZone: http://localhost:8761/eureka/