server:
  port: 8088
spring:
  application.name: payment-service

# eureka
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl.defaultZone: http://localhost:8761/eureka/

# paypal
paypal:
  clientId: ATnSZawIDfxL55EZMcieHYkK79_MrJJqubPJnqXEoXkWSiF7tnv1DfcJbH5SpmpGLFxSyqTwQ6Co1FWN
  clientSecret: EByq2lEqNvLLf412qAuYPWBZdCW0UO_9XSjGa8Ez3c_Xa_rqtkvTKPIUtIPgPIDn-e4Mq8PZZJraPkza