server:
  port: 8082
spring:
  application.name: user-service

  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      name: db-docker,user-service-docker,eureka
  config.import: optional:configserver:config-server