server:
  port: 8087
spring:
  application.name: order-service

  # database
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      name: database

  # set up initial data
  sql.init.mode: always
  jpa.defer-datasource-initialization: true

  # kafka
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# eureka
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl.defaultZone: http://localhost:8761/eureka/