server:
  port: 8087
spring:
  application.name: order-service

  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      name: db-docker,order-service-docker,kafka-producer,eureka
  config.import: optional:configserver:config-server