server:
  port: 8087
spring:
  application.name: order-service

  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      name: order-service,db,eureka
  config.import: optional:configserver:config-server

  # kafka
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer