server:
  port: 8084
spring:
  application.name: product-service

  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      name: product-service,db,eureka
  config.import: optional:configserver:config-server