server:
  port: 8084
spring:
  application.name: product-service

  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      #name: db-local,product-service-local,eureka
      name: db-docker,product-service-docker,eureka
  config.import: optional:configserver:config-server