version: '3'

services:
  eureka-server:
    image: eureka-server:latest
    restart: on-failure
    container_name: eureka-server
    ports:
      - 8761:8761

  config-server:
    image: config-server:latest
    restart: always
    container_name: config-server
    ports:
      - 8888:8888
    depends_on:
      - eureka-server
    environment:
      eureka.client.service-url.defaultZone: http://host.docker.internal:8761/eureka/

  db-user:
    image: postgres:alpine
    container_name: db-user
    environment:
      POSTGRES_PASSWORD: 500290
      POSTGRES_USER: users

  user-service:
    image: user-service:latest
    container_name: user-service
    restart: always
    ports:
      - 8082:8082
    depends_on:
      - config-server
      - db-user
    environment:
      eureka.client.service-url.defaultZone: http://host.docker.internal:8761/eureka/