server:
  port: 8083
spring:
  application.name: address-service

apiKey: 84fe3816-116e-4992-af87-165c20b2f2c4
apiResource: https://graphhopper.com/api/1

# eureka
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl.defaultZone: http://localhost:8761/eureka/