server:
  port: 8083
spring:
  application.name: address-service

  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      name: eureka
    config.import: optional:configserver:config-server

apiKey: 84fe3816-116e-4992-af87-165c20b2f2c4
apiResource: https://graphhopper.com/api/1